set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSTEM_VERSION 1)

set(TOOLCHAIN_PATH "" CACHE PATH
    "Path to arm-none-linux-gnueabihf toolchain bin directory")
set(SYSROOT_PATH "" CACHE PATH "Optional target sysroot directory")

if(SYSROOT_PATH)
    if(NOT EXISTS "${SYSROOT_PATH}")
        message(FATAL_ERROR "SYSROOT_PATH does not exist: ${SYSROOT_PATH}")
    endif()
    set(CMAKE_SYSROOT "${SYSROOT_PATH}")
endif()

set(_COMPILER_PREFIX "arm-none-linux-gnueabihf")

if(TOOLCHAIN_PATH)
    set(_TOOLCHAIN_HINTS "${TOOLCHAIN_PATH}")
else()
    file(GLOB _TOOLCHAIN_HINTS
        "C:/kk_software/toolchain/*${_COMPILER_PREFIX}*/bin")
endif()

find_program(CMAKE_C_COMPILER NAMES ${_COMPILER_PREFIX}-gcc
    HINTS ${_TOOLCHAIN_HINTS} PATHS ENV PATH REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES ${_COMPILER_PREFIX}-g++
    HINTS ${_TOOLCHAIN_HINTS} PATHS ENV PATH REQUIRED)
find_program(CMAKE_AR NAMES ${_COMPILER_PREFIX}-ar
    HINTS ${_TOOLCHAIN_HINTS} PATHS ENV PATH REQUIRED)
find_program(CMAKE_RANLIB NAMES ${_COMPILER_PREFIX}-ranlib
    HINTS ${_TOOLCHAIN_HINTS} PATHS ENV PATH)
find_program(CMAKE_STRIP NAMES ${_COMPILER_PREFIX}-strip
    HINTS ${_TOOLCHAIN_HINTS} PATHS ENV PATH)

if(CMAKE_SYSROOT)
    set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

