set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSTEM_VERSION 1)

set(TOOLCHAIN_PATH "" CACHE PATH
    "Path to arm-none-linux-gnueabihf toolchain bin directory. Leave empty to search PATH.")
set(SYSROOT_PATH "" CACHE PATH
    "Path to target sysroot directory. Leave empty to use the compiler sysroot.")

if(SYSROOT_PATH)
    if(NOT EXISTS "${SYSROOT_PATH}")
        message(FATAL_ERROR "SYSROOT_PATH does not exist: ${SYSROOT_PATH}")
    endif()
    set(CMAKE_SYSROOT "${SYSROOT_PATH}")
endif()

set(_COMPILER_PREFIX "arm-none-linux-gnueabihf")
if(TOOLCHAIN_PATH)
    set(CMAKE_C_COMPILER "${TOOLCHAIN_PATH}/${_COMPILER_PREFIX}-gcc")
    set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PATH}/${_COMPILER_PREFIX}-g++")
    set(CMAKE_AR "${TOOLCHAIN_PATH}/${_COMPILER_PREFIX}-ar")
    set(CMAKE_RANLIB "${TOOLCHAIN_PATH}/${_COMPILER_PREFIX}-ranlib")
    set(CMAKE_STRIP "${TOOLCHAIN_PATH}/${_COMPILER_PREFIX}-strip")
else()
    file(GLOB _LOCAL_TOOLCHAIN_BIN_CANDIDATES
        "C:/kk_software/toolchain/*${_COMPILER_PREFIX}*/bin")
    find_program(CMAKE_C_COMPILER NAMES ${_COMPILER_PREFIX}-gcc
        HINTS ${_LOCAL_TOOLCHAIN_BIN_CANDIDATES} PATHS ENV PATH REQUIRED)
    find_program(CMAKE_CXX_COMPILER NAMES ${_COMPILER_PREFIX}-g++
        HINTS ${_LOCAL_TOOLCHAIN_BIN_CANDIDATES} PATHS ENV PATH REQUIRED)
    find_program(CMAKE_AR NAMES ${_COMPILER_PREFIX}-ar
        HINTS ${_LOCAL_TOOLCHAIN_BIN_CANDIDATES} PATHS ENV PATH REQUIRED)
    find_program(CMAKE_RANLIB NAMES ${_COMPILER_PREFIX}-ranlib
        HINTS ${_LOCAL_TOOLCHAIN_BIN_CANDIDATES} PATHS ENV PATH)
    find_program(CMAKE_STRIP NAMES ${_COMPILER_PREFIX}-strip
        HINTS ${_LOCAL_TOOLCHAIN_BIN_CANDIDATES} PATHS ENV PATH)
endif()

if(CMAKE_SYSROOT)
    set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
